### ISSUE TITLE
我的朋友们 - LHK's Blog

### ISSUE THREAD

**Issue by Reqwey** [Reqwey/blog-source#13]
https://blog.lhkstudio.me/friends/ 

 友 链

**Comment by inkss** [comment]
替换下友链图片地址：`https://cdn.jsdelivr.net/gh/inkss/common@master/static/web/avatar.jpg`

**Comment by Linhk1606** [comment]
> @inkss
> 替换下友链图片地址：`https://cdn.jsdelivr.net/gh/inkss/common@master/static/web/avatar.jpg`

OK, ghactions已经在跑了 BTW, 下次可以直接PR哦

**Comment by inkss** [comment]
a hhh, 我把我图床的 cdn 开了防盗链，所以原先的引用就得换了
