### ISSUE TITLE
CSP-S2020游记 - LHK的OI博客

### ISSUE THREAD

**Issue by Reqwey** [Reqwey/blog-source#29]
https://blog.lhkstudio.me/2020/11/09/yuque/CSP-S2020%E6%B8%B8%E8%AE%B0/ 

 一只蒟蒻的博客...

**Comment by Linhk1606** [comment]
由于是在第三方平台发布的, 因此公式渲染可能会有点问题, 凑合着看吧

**Comment by xiao-lin52** [comment]
话说 T1 不用考虑那么多段吧，我只考虑了 1582 年 10 月 4 日之前和 1582 年 10 月 15 日之后这两段

T3 没看是真的可惜，我暴力 DFS 加分块拿了 70 pts

**Comment by Linhk1606** [comment]
> @xiao-lin52
> 话说 T1 不用考虑那么多段吧，我只考虑了 1582 年 10 月 4 日之前和 1582 年 10 月 15 日之后这两段
> 
> T3 没看是真的可惜，我暴力 DFS 加分块拿了 70 pts

这 确实可惜, 我太菜了qaq
不过我T3现在会做了

**Comment by Linhk1606** [comment]
> @xiao-lin52
> 话说 T1 不用考虑那么多段吧，我只考虑了 1582 年 10 月 4 日之前和 1582 年 10 月 15 日之后这两段
> 
> T3 没看是真的可惜，我暴力 DFS 加分块拿了 70 pts

大佬换友链不?

**Comment by xiao-lin52** [comment]
> @Linhk1606
> > @xiao-lin52
> > 话说 T1 不用考虑那么多段吧，我只考虑了 1582 年 10 月 4 日之前和 1582 年 10 月 15 日之后这两段
> > 
> > T3 没看是真的可惜，我暴力 DFS 加分块拿了 70 pts
> 
> 大佬换友链不?

好啊

**Comment by jalenchuh** [comment]
图片一直显示 loading

**Comment by Linhk1606** [comment]
> @jalenchuh
> 图片一直显示 loading

pjax的锅，我根本不会修，何况这个版本的主题我都忘记怎么维护了
